import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'SALIDA', desc: 'Cobra $200 al pasar' },
  { name: 'Calle del Molino' },
  { name: 'Sorpresa' },
  { name: 'Avenida del Río' },
  { name: 'Impuesto', desc: 'Paga $200' },
  { name: 'Metro Norte' },
  { name: 'Plaza Mayor' },
  { name: 'Fortuna' },
  { name: 'Mercado Central' },
  { name: 'Paseo Marítimo' },
  { name: 'Comisaría', desc: 'Solo visita' },
  { name: 'Calle Rosa' },
  { name: 'Agua Municipal' },
  { name: 'Avenida Flores' },
  { name: 'Jardín Botánico' },
  { name: 'Metro Sur' },
  { name: 'Campus Norte' },
  { name: 'Sorpresa' },
  { name: 'Biblioteca' },
  { name: 'Facultad de Arte' },
  { name: 'Zona Libre', desc: 'Descansa aquí' },
  { name: 'Muelle 1' },
  { name: 'Fortuna' },
  { name: 'Muelle 2' },
  { name: 'Almacén Portuario' },
  { name: 'Metro Este' },
  { name: 'Terminal A' },
  { name: 'Terminal B' },
  { name: 'Energía Urbana' },
  { name: 'Hangar' },
  { name: '¡A la Comisaría!', desc: 'Ve directo a la cárcel' },
  { name: 'Torre Financiera' },
  { name: 'Rascacielos Norte' },
  { name: 'Sorpresa' },
  { name: 'Parque Central' },
  { name: 'Metro Oeste' },
  { name: 'Fortuna' },
  { name: 'Torre del Cielo' },
  { name: 'Tasa de Lujo', desc: 'Paga $100' },
  { name: 'Gran Torre' },
];

export default {
  id: 'default',
  name: 'Imperio Urbano',
  icon: '🏙️',
  tagline: 'Construye tu imperio inmobiliario en la gran ciudad.',

  defaultPlayerNames: ['Magnate', 'Inversor', 'Empresario', 'Constructor', 'Visionario', 'Capitalista'],

  colors: {
    brown: { bg: '#8B4513', light: '#D2691E', name: 'Barrio Antiguo' },
    lightblue: { bg: '#87CEEB', light: '#B0E0E6', name: 'Costa' },
    pink: { bg: '#FF69B4', light: '#FFB6C1', name: 'Centro' },
    orange: { bg: '#FF8C00', light: '#FFA500', name: 'Universidad' },
    red: { bg: '#DC143C', light: '#F08080', name: 'Puerto' },
    yellow: { bg: '#FFD700', light: '#FFFACD', name: 'Aeropuerto' },
    green: { bg: '#228B22', light: '#90EE90', name: 'Parque' },
    darkblue: { bg: '#00008B', light: '#4169E1', name: 'Rascacielos' },
    railroad: { bg: '#2F4F4F', light: '#708090', name: 'Metro' },
    utility: { bg: '#C0C0C0', light: '#E8E8E8', name: 'Servicios' },
  },

  playerColors: ['#E74C3C', '#3498DB', '#2ECC71', '#F39C12', '#9B59B6', '#1ABC9C'],

  tokens: [
    { id: 'car', name: 'Auto deportivo', icon: 'fa-car-side' },
    { id: 'rocket', name: 'Cohete', icon: 'fa-rocket' },
    { id: 'tower', name: 'Torre', icon: 'fa-building' },
    { id: 'ship', name: 'Yate', icon: 'fa-ship' },
    { id: 'plane', name: 'Avión', icon: 'fa-plane' },
    { id: 'crown', name: 'Corona', icon: 'fa-crown' },
    { id: 'gem', name: 'Diamante', icon: 'fa-gem' },
    { id: 'train', name: 'Tren', icon: 'fa-train-subway' },
    { id: 'helicopter', name: 'Helicóptero', icon: 'fa-helicopter' },
    { id: 'knight', name: 'Caballo', icon: 'fa-chess-knight' },
    { id: 'trophy', name: 'Trofeo', icon: 'fa-trophy' },
    { id: 'key', name: 'Llave', icon: 'fa-key' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta SALIDA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Avanza hasta Metro Norte. Si pasas por SALIDA, cobra $200.', action: 'move', target: 5 },
    { text: 'Avanza hasta Metro Sur. Si pasas por SALIDA, cobra $200.', action: 'move', target: 15 },
    { text: 'Avanza hasta Metro Este. Si pasas por SALIDA, cobra $200.', action: 'move', target: 25 },
    { text: 'Avanza hasta Metro Oeste. Si pasas por SALIDA, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza hasta la casilla más cercana de Servicios. Si no está comprada, puedes comprarla.', action: 'nearest', type: 'utility' },
    { text: 'Avanza hasta la casilla más cercana de Metro. Si no está comprada, puedes comprarla.', action: 'nearest', type: 'railroad' },
    { text: 'El banco te devuelve $50 de impuestos.', action: 'money', amount: 50 },
    { text: 'Ganas un concurso de belleza arquitectónica. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Sal de la Comisaría gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡A la Comisaría! Ve directo sin pasar por SALIDA.', action: 'gotojail' },
    { text: 'Retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Eres presidente del consejo vecinal. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Reparaciones urgentes: $25 por edificio y $100 por rascacielos.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa por exceso de velocidad: paga $15.', action: 'money', amount: -15 },
    { text: 'Toma el tren hasta la siguiente estación de Metro.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta SALIDA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Herencia inesperada. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Dividendos de inversión. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Cumpleaños del alcalde. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Reembolso de impuestos. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Seguro de vida. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Ganas el segundo premio en un concurso. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Vendes tu colección de sellos. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Honorarios del hospital. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Sal de la Comisaría gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Paga reparación de calles: $40.', action: 'money', amount: -40 },
    { text: 'Multa de estacionamiento: $15.', action: 'money', amount: -15 },
    { text: 'Visita al médico: paga $50.', action: 'money', amount: -50 },
    { text: 'Matrícula universitaria: paga $50.', action: 'money', amount: -50 },
    { text: 'Reparaciones en tus propiedades: $25 por edificio y $100 por rascacielos.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡A la Comisaría! Ve directo sin pasar por SALIDA.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Imperio Urbano',
    centerTitle: 'Imperio Urbano',
    centerTagline: 'Domina la ciudad',
    welcomeLog: '¡Bienvenidos a Imperio Urbano! Que gane el mejor inversionista.',
    winMessage: 'Ha dominado la ciudad con astucia y fortuna.',
    goName: 'SALIDA',
    jailName: 'Comisaría',
    parkingName: 'Zona Libre',
    chanceName: 'Sorpresa',
    fortuneName: 'Fortuna',
    chanceDeckTitle: '🃏 Sorpresa Ciudad',
    fortuneDeckTitle: '🎁 Fortuna',
    railroadLabel: 'Estación de Metro',
    utilityLabel: 'Servicio público',
    jailFreeCard: 'carta de salida de la Comisaría',
    jailEmoji: '🚔',
    parkingEmoji: '🅿️',
    buildings: {
      house: 'edificio',
      houses: 'edificios',
      houseEmoji: '🏢',
      houseMarker: '▪',
      hotel: 'rascacielos',
      hotels: 'rascacielos',
      hotelEmoji: '🏙️',
      rowLabel: 'Construcciones',
      buildHouse: 'Edificio',
      buildHotel: 'Rascacielos',
      supplyHouses: 'Edificios',
      supplyHotels: 'Rascacielos',
      noHousesLeft: 'No quedan edificios en el banco.',
      noHotelsLeft: 'No quedan rascacielos en el banco.',
      sellBeforeMortgage: 'Vende las construcciones antes de hipotecar.',
      sellFundsHint: 'Hipoteca propiedades o vende edificios en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>SALIDA</strong> y cobra $200',
      'Compra propiedades, cobra alquileres y construye <strong>edificios y rascacielos</strong>',
      'Completa grupos de color para monopolio y construcción',
      '<strong>Negocia</strong> propiedades, dinero y cartas con otros jugadores',
      'Si no compras, la propiedad se <strong>subasta</strong> entre todos',
      'Impuestos y multas van al fondo de <strong>Zona Libre</strong>',
      'Hipoteca propiedades para obtener liquidez rápida',
      'El último jugador en pie gana la ciudad',
    ],
  },

  style: {
    fontFamily: "'Outfit', system-ui, sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&display=swap',
    bodyBg: `
      radial-gradient(circle at 15% 10%, rgba(240,165,0,0.16), transparent 28%),
      radial-gradient(circle at 85% 20%, rgba(52,152,219,0.12), transparent 30%),
      linear-gradient(135deg, #081018 0%, #0f1419 54%, #111827 100%)`,
    vars: {
      '--bg': '#0f1419',
      '--surface': '#1a2332',
      '--surface2': '#243044',
      '--accent': '#f0a500',
      '--accent2': '#e74c3c',
      '--text': '#e8ecf1',
      '--text-muted': '#8899aa',
      '--board-bg': '#1e6b3a',
      '--board-border': '#145a2e',
      '--board-center-bg': 'radial-gradient(ellipse at center, #2d8a4e, #1a5c32)',
      '--cell-bg': '#f5f0e1',
      '--cell-text': '#2c2c2c',
    },
  },
};
