import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'SAQUE DE CENTRO', desc: 'Cobra $200 al completar una vuelta' },
  { name: 'Ajax' },
  { name: 'VAR' },
  { name: 'Benfica' },
  { name: 'Multa FIFA', desc: 'Paga $200' },
  { name: 'Ruta Wembley' },
  { name: 'Inter de Milán' },
  { name: 'Copa del Mundo' },
  { name: 'AC Milan' },
  { name: 'Napoli' },
  { name: 'Tarjeta Roja', desc: 'Solo visita' },
  { name: 'Arsenal' },
  { name: 'Derechos TV' },
  { name: 'Chelsea' },
  { name: 'Liverpool' },
  { name: 'Ruta Bernabéu' },
  { name: 'Real Madrid' },
  { name: 'VAR' },
  { name: 'Barcelona' },
  { name: 'Atlético Madrid' },
  { name: 'Vestuario', desc: 'Descansa aquí' },
  { name: 'Bayern Múnich' },
  { name: 'Copa del Mundo' },
  { name: 'Borussia Dortmund' },
  { name: 'Juventus' },
  { name: 'Ruta Old Trafford' },
  { name: 'Manchester City' },
  { name: 'Manchester United' },
  { name: 'Patrocinio Global' },
  { name: 'Paris Saint-Germain' },
  { name: '¡Al Vestuario!', desc: 'Expulsado sin pasar por SAQUE DE CENTRO' },
  { name: 'Boca Juniors' },
  { name: 'River Plate' },
  { name: 'VAR' },
  { name: 'Flamengo' },
  { name: 'Ruta Maracaná' },
  { name: 'Copa del Mundo' },
  { name: 'Corinthians' },
  { name: 'Impuesto UEFA', desc: 'Paga $100' },
  { name: 'Inter Miami' },
];

export default {
  id: 'football',
  name: 'Fútbol Mundial',
  icon: '⚽',
  tagline: 'Conquista clubes legendarios y domina el fútbol planetario.',

  defaultPlayerNames: ['Messi', 'Pelé', 'Maradona', 'Ronaldo', 'Zidane', 'Cruyff'],

  colors: {
    brown: { bg: '#78350F', light: '#FCD34D', name: 'Europa Clásica' },
    lightblue: { bg: '#0369A1', light: '#7DD3FC', name: 'Calcio' },
    pink: { bg: '#BE123C', light: '#FDA4AF', name: 'Premier League' },
    orange: { bg: '#C2410C', light: '#FDBA74', name: 'La Liga' },
    red: { bg: '#991B1B', light: '#FCA5A5', name: 'Bundesliga & Serie A' },
    yellow: { bg: '#A16207', light: '#FDE047', name: 'Superclubes' },
    green: { bg: '#166534', light: '#86EFAC', name: 'Sudamérica' },
    darkblue: { bg: '#1E3A8A', light: '#93C5FD', name: 'Ídolos Globales' },
    railroad: { bg: '#334155', light: '#94A3B8', name: 'Rutas Legendarias' },
    utility: { bg: '#0F766E', light: '#5EEAD4', name: 'Negocios del Fútbol' },
  },

  playerColors: ['#EF4444', '#2563EB', '#16A34A', '#EAB308', '#9333EA', '#0891B2'],

  tokens: [
    { id: 'ball', name: 'Balón', icon: 'fa-futbol' },
    { id: 'trophy', name: 'Copa', icon: 'fa-trophy' },
    { id: 'boot', name: 'Botín', icon: 'fa-shoe-prints' },
    { id: 'whistle', name: 'Silbato', icon: 'fa-bullhorn' },
    { id: 'star', name: 'Estrella', icon: 'fa-star' },
    { id: 'medal', name: 'Medalla', icon: 'fa-medal' },
    { id: 'flag', name: 'Bandera', icon: 'fa-flag' },
    { id: 'fire', name: 'Pasión', icon: 'fa-fire' },
    { id: 'crown', name: 'Campeón', icon: 'fa-crown' },
    { id: 'shield', name: 'Escudo', icon: 'fa-shield-halved' },
    { id: 'heart', name: 'Hincha', icon: 'fa-heart' },
    { id: 'bolt', name: 'Contraataque', icon: 'fa-bolt' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta SAQUE DE CENTRO. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Traslado a Ruta Wembley. Si pasas por SAQUE DE CENTRO, cobra $200.', action: 'move', target: 5 },
    { text: 'Traslado a Ruta Bernabéu. Si pasas por SAQUE DE CENTRO, cobra $200.', action: 'move', target: 15 },
    { text: 'Traslado a Ruta Old Trafford. Si pasas por SAQUE DE CENTRO, cobra $200.', action: 'move', target: 25 },
    { text: 'Traslado a Ruta Maracaná. Si pasas por SAQUE DE CENTRO, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza al negocio más cercano. Si no está comprado, puedes adquirirlo.', action: 'nearest', type: 'utility' },
    { text: 'Avanza a la ruta legendaria más cercana. Si no está comprada, puedes adquirirla.', action: 'nearest', type: 'railroad' },
    { text: 'Premio fair play de la UEFA: cobra $50.', action: 'money', amount: 50 },
    { text: 'Ganas el partido amistoso de pretemporada. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Apelación exitosa: sal del Vestuario gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡Al Vestuario! Expulsado sin pasar por SAQUE DE CENTRO.', action: 'gotojail' },
    { text: 'Lesión en el calentamiento: retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Organizas un partido benéfico. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Mantenimiento del estadio: $25 por grada y $100 por palco VIP.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa por fair play financiero: paga $15.', action: 'money', amount: -15 },
    { text: 'Toma la siguiente ruta legendaria disponible.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta SAQUE DE CENTRO. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Prima por ganar la Champions. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Bonus por clasificar a octavos. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Tu equipo gana el clásico local. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Venta de entradas récord. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Seguro del plantel titular. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Subcampeón de liga. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Merchandising del escudo. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Derechos de imagen del crack. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Apelación exitosa: sal del Vestuario gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Reparación del césped: $40.', action: 'money', amount: -40 },
    { text: 'Multa por protesta al árbitro: $15.', action: 'money', amount: -15 },
    { text: 'Operación del goleador: $50.', action: 'money', amount: -50 },
    { text: 'Fichaje fallido en el mercado: $50.', action: 'money', amount: -50 },
    { text: 'Mantenimiento en tus clubes: $25 por grada, $100 por palco VIP.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡Al Vestuario! Expulsado sin pasar por SAQUE DE CENTRO.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Fútbol Mundial',
    centerTitle: 'Fútbol Mundial',
    centerTagline: 'Un balón, un sueño, un imperio',
    welcomeLog: '¡Arranca el partido! Que gane quien domine el fútbol mundial.',
    winMessage: 'Ha levantado la copa más grande del tablero.',
    goName: 'SAQUE DE CENTRO',
    jailName: 'Vestuario',
    parkingName: 'Vestuario Libre',
    chanceName: 'VAR',
    fortuneName: 'Copa del Mundo',
    chanceDeckTitle: '📺 VAR',
    fortuneDeckTitle: '🏆 Copa del Mundo',
    railroadLabel: 'Ruta legendaria',
    utilityLabel: 'Negocio del fútbol',
    jailFreeCard: 'apelación exitosa',
    jailEmoji: '🟥',
    parkingEmoji: '🧤',
    buildings: {
      house: 'grada',
      houses: 'gradas',
      houseEmoji: '🏟️',
      houseMarker: '▪',
      hotel: 'palco VIP',
      hotels: 'palcos VIP',
      hotelEmoji: '👑',
      rowLabel: 'Instalaciones',
      buildHouse: 'Grada',
      buildHotel: 'Palco VIP',
      supplyHouses: 'Gradas',
      supplyHotels: 'Palcos VIP',
      noHousesLeft: 'No quedan gradas en el banco.',
      noHotelsLeft: 'No quedan palcos VIP en el banco.',
      sellBeforeMortgage: 'Vende gradas y palcos antes de hipotecar.',
      sellFundsHint: 'Hipoteca clubes o vende gradas/palcos en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>SAQUE DE CENTRO</strong> y cobra $200',
      'Compra clubes, cobra peajes y construye <strong>gradas y palcos VIP</strong>',
      'Completa ligas del mismo color para monopolio',
      '<strong>Negocia</strong> fichajes, dinero y apelaciones con otros directores',
      'Si no compras, el club se <strong>subasta</strong>',
      'Multas y tasas van al <strong>Vestuario Libre</strong>',
      'Hipoteca clubes para levantar fondos de mercado',
      'El último campeón en pie gana el tablero',
    ],
  },

  style: {
    fontFamily: "'Outfit', system-ui, sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&display=swap',
    bodyBg: `
      radial-gradient(circle at 18% 14%, rgba(34,197,94,0.18), transparent 32%),
      radial-gradient(circle at 82% 20%, rgba(59,130,246,0.16), transparent 30%),
      linear-gradient(135deg, #052e16 0%, #0f172a 55%, #14532d 100%)`,
    vars: {
      '--bg': '#0f172a',
      '--surface': '#1e293b',
      '--surface2': '#334155',
      '--accent': '#22c55e',
      '--accent2': '#eab308',
      '--text': '#f8fafc',
      '--text-muted': '#94a3b8',
      '--board-bg': '#15803d',
      '--board-border': '#166534',
      '--board-center-bg': 'radial-gradient(ellipse at center, #16a34a, #14532d)',
      '--cell-bg': '#ecfdf5',
      '--cell-text': '#14532d',
    },
  },
};
