import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'SALIDA', desc: 'Cobra $200 al dar la vuelta al continente' },
  { name: 'Guatemala' },
  { name: 'La Bola' },
  { name: 'El Salvador' },
  { name: 'Aduana Fronteriza', desc: 'Paga $200' },
  { name: 'Ruta Caribeña' },
  { name: 'Cuba' },
  { name: 'El Trago' },
  { name: 'Rep. Dominicana' },
  { name: 'Puerto Rico' },
  { name: 'La Resaca', desc: 'Solo visita' },
  { name: 'Colombia' },
  { name: 'Petróleo y Gas' },
  { name: 'Venezuela' },
  { name: 'Ecuador' },
  { name: 'Ruta Andina' },
  { name: 'Perú' },
  { name: 'La Bola' },
  { name: 'Bolivia' },
  { name: 'Paraguay' },
  { name: 'Zona Chill', desc: 'Descansa aquí' },
  { name: 'Brasil' },
  { name: 'El Trago' },
  { name: 'Uruguay' },
  { name: 'Chile' },
  { name: 'Ruta del Sur' },
  { name: 'Argentina' },
  { name: 'México' },
  { name: 'Energía Verde' },
  { name: 'Panamá' },
  { name: '¡A la Resaca!', desc: 'Directo sin pasar por SALIDA' },
  { name: 'Nicaragua' },
  { name: 'Costa Rica' },
  { name: 'La Bola' },
  { name: 'Belice' },
  { name: 'Ruta Pacífico' },
  { name: 'El Trago' },
  { name: 'Ciudad de México' },
  { name: 'Impuesto VIP', desc: 'Paga $100' },
  { name: 'São Paulo' },
];

export default {
  id: 'latam',
  name: 'Latinoamérica',
  icon: '🌎',
  tagline: 'Conquista naciones, rutas y recursos del continente.',

  colors: {
    brown: { bg: '#7C2D12', light: '#EA580C', name: 'Centroamérica' },
    lightblue: { bg: '#0891B2', light: '#67E8F9', name: 'Caribe' },
    pink: { bg: '#DB2777', light: '#F9A8D4', name: 'Norte Suramericano' },
    orange: { bg: '#C2410C', light: '#FB923C', name: 'Altiplano' },
    red: { bg: '#B91C1C', light: '#FCA5A5', name: 'Cono Sur Atlántico' },
    yellow: { bg: '#CA8A04', light: '#FDE047', name: 'Potencias Regionales' },
    green: { bg: '#15803D', light: '#86EFAC', name: 'Istmo y Pacífico' },
    darkblue: { bg: '#1E3A8A', light: '#60A5FA', name: 'Megaciudades' },
    railroad: { bg: '#0D9488', light: '#5EEAD4', name: 'Rutas Panamericanas' },
    utility: { bg: '#57534E', light: '#A8A29E', name: 'Recursos' },
  },

  playerColors: ['#DC2626', '#2563EB', '#16A34A', '#EAB308', '#9333EA', '#0891B2'],

  tokens: [
    { id: 'maracas', name: 'Maracas', icon: 'fa-music' },
    { id: 'guitar', name: 'Guitarra', icon: 'fa-guitar' },
    { id: 'soccer', name: 'Pelota', icon: 'fa-futbol' },
    { id: 'sun', name: 'Sol tropical', icon: 'fa-sun' },
    { id: 'beach', name: 'Playa', icon: 'fa-umbrella-beach' },
    { id: 'pepper', name: 'Ají picante', icon: 'fa-pepper-hot' },
    { id: 'coffee', name: 'Café', icon: 'fa-mug-hot' },
    { id: 'drum', name: 'Tambor', icon: 'fa-drum' },
    { id: 'mask', name: 'Carnaval', icon: 'fa-masks-theater' },
    { id: 'tree', name: 'Selva', icon: 'fa-tree' },
    { id: 'mountain', name: 'Andes', icon: 'fa-mountain' },
    { id: 'compass', name: 'Brújula', icon: 'fa-compass' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta SALIDA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Vuelo a Ruta Caribeña. Si pasas por SALIDA, cobra $200.', action: 'move', target: 5 },
    { text: 'Vuelo a Ruta Andina. Si pasas por SALIDA, cobra $200.', action: 'move', target: 15 },
    { text: 'Vuelo a Ruta del Sur. Si pasas por SALIDA, cobra $200.', action: 'move', target: 25 },
    { text: 'Vuelo a Ruta Pacífico. Si pasas por SALIDA, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza al recurso más cercano. Si no está comprado, puedes adquirirlo.', action: 'nearest', type: 'utility' },
    { text: 'Avanza a la ruta panamericana más cercana. Si no está comprada, puedes adquirirla.', action: 'nearest', type: 'railroad' },
    { text: 'Subvención del Banco del Sur: cobra $50.', action: 'money', amount: 50 },
    { text: 'Ganas el concurso de carnaval. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Pase diplomático. Sal de La Resaca gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡A La Resaca! Control migratorio sin pasar por SALIDA.', action: 'gotojail' },
    { text: 'Retraso en aduana: retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Organizas la Cumbre Latinoamericana. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Mantenimiento de infraestructura: $25 por rancho y $100 por hacienda.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa por exceso de equipaje: paga $15.', action: 'money', amount: -15 },
    { text: 'Toma la siguiente ruta panamericana disponible.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta SALIDA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Herencia del abuelo emigrante. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Exportación de café y soja. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Día de la independencia de tu país. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Devolución de impuestos aduaneros. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Seguro de exportación. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Segundo premio en el festival folclórico. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Vendes artesanías en la feria. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Consultoría para la OEA. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Pase diplomático. Sal de La Resaca gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Reparación de carreteras: $40.', action: 'money', amount: -40 },
    { text: 'Peaje en la panamericana: $15.', action: 'money', amount: -15 },
    { text: 'Visita al médico en el extranjero: $50.', action: 'money', amount: -50 },
    { text: 'Matrícula en universidad pública: $50.', action: 'money', amount: -50 },
    { text: 'Mantenimiento en tus territorios: $25 por rancho, $100 por hacienda.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡A La Resaca! Control migratorio sin pasar por SALIDA.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Latinoamérica',
    centerTitle: 'Latinoamérica',
    centerTagline: 'Del Caribe al Cono Sur',
    welcomeLog: '¡Bienvenidos al continente! Que gane quien domine Latinoamérica.',
    winMessage: 'Ha conquistado Latinoamérica con astucia y sazón.',
    goName: 'SALIDA',
    jailName: 'La Resaca',
    parkingName: 'Zona Chill',
    chanceName: 'La Bola',
    fortuneName: 'El Trago',
    chanceDeckTitle: '🌴 Carta La Bola',
    fortuneDeckTitle: '🍹 El Trago',
    railroadLabel: 'Ruta Panamericana',
    utilityLabel: 'Recurso estratégico',
    jailFreeCard: 'pase diplomático',
    jailEmoji: '🛃',
    parkingEmoji: '😎',
    buildings: {
      house: 'rancho',
      houses: 'ranchos',
      houseEmoji: '🏡',
      houseMarker: '▪',
      hotel: 'hacienda',
      hotels: 'haciendas',
      hotelEmoji: '🏛️',
      rowLabel: 'Propiedades',
      buildHouse: 'Rancho',
      buildHotel: 'Hacienda',
      supplyHouses: 'Ranchos',
      supplyHotels: 'Haciendas',
      noHousesLeft: 'No quedan ranchos en el banco.',
      noHotelsLeft: 'No quedan haciendas en el banco.',
      sellBeforeMortgage: 'Vende ranchos y haciendas antes de hipotecar.',
      sellFundsHint: 'Hipoteca territorios o vende ranchos/haciendas en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>SALIDA</strong> y cobra $200',
      'Compra países, cobra peajes y construye <strong>ranchos y haciendas</strong>',
      'Completa regiones del mismo color para monopolio',
      '<strong>Negocia</strong> territorios, dinero y pases con otros jugadores',
      'Si no compras, el territorio se <strong>subasta</strong>',
      'Impuestos y multas van a la <strong>Zona Chill</strong>',
      'Hipoteca territorios para obtener liquidez',
      'El último jugador en pie domina el continente',
    ],
  },

  style: {
    fontFamily: "'Outfit', system-ui, sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&display=swap',
    bodyBg: `
      radial-gradient(circle at 15% 12%, rgba(234,88,12,0.22), transparent 30%),
      radial-gradient(circle at 85% 20%, rgba(22,163,74,0.18), transparent 32%),
      radial-gradient(circle at 50% 80%, rgba(220,38,38,0.12), transparent 35%),
      linear-gradient(135deg, #1a0a05 0%, #1c1917 50%, #292524 100%)`,
    vars: {
      '--bg': '#1c1917',
      '--surface': '#292524',
      '--surface2': '#44403c',
      '--accent': '#ea580c',
      '--accent2': '#dc2626',
      '--text': '#fafaf9',
      '--text-muted': '#a8a29e',
      '--board-bg': '#15803d',
      '--board-border': '#166534',
      '--board-center-bg': 'radial-gradient(ellipse at center, #22c55e, #15803d)',
      '--cell-bg': '#fef9c3',
      '--cell-text': '#292524',
    },
  },
};
