import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'LA COMARCA', desc: 'Cobra $200 al pasar' },
  { name: 'Bolsón Cerrado' },
  { name: 'Destino' },
  { name: 'Hobbiton' },
  { name: 'Tributo Real', desc: 'Paga $200' },
  { name: 'Camino del Norte' },
  { name: 'Rivendel' },
  { name: 'Saber' },
  { name: 'Bree' },
  { name: 'Fornost' },
  { name: 'Solo visita', desc: 'Mazmorras de Barad-dûr — visita' },
  { name: 'Edoras' },
  { name: 'Palantír' },
  { name: 'Helm\'s Deep' },
  { name: 'Rohan' },
  { name: 'Camino del Sur' },
  { name: 'Osgiliath' },
  { name: 'Destino' },
  { name: 'Minas Tirith' },
  { name: 'Pelennor' },
  { name: 'Tierras Libres', desc: 'Descansa aquí' },
  { name: 'Mordor Norte' },
  { name: 'Saber' },
  { name: 'Barad-dûr' },
  { name: 'Gorgoroth' },
  { name: 'Camino del Este' },
  { name: 'Harad' },
  { name: 'Rhûn' },
  { name: 'Fuego de Dragón' },
  { name: 'Umbar' },
  { name: '¡A las Mazmorras de Barad-dur!', desc: 'Capturado por orcos' },
  { name: 'Lórien' },
  { name: 'Fangorn' },
  { name: 'Destino' },
  { name: 'Erebor' },
  { name: 'Camino del Oeste' },
  { name: 'Saber' },
  { name: 'Gondolin' },
  { name: 'Impuesto Élfico', desc: 'Paga $100' },
  { name: 'Valinor' },
];

export default {
  id: 'lotr',
  name: 'Tierra Media',
  icon: '💍',
  tagline: 'Recorre la Tierra Media, forja alianzas y conquista reinos.',

  colors: {
    brown: { bg: '#5D4037', light: '#A1887F', name: 'La Comarca' },
    lightblue: { bg: '#4FC3F7', light: '#B3E5FC', name: 'Eriador' },
    pink: { bg: '#C2185B', light: '#F48FB1', name: 'Rohan' },
    orange: { bg: '#E65100', light: '#FFCC80', name: 'Gondor Menor' },
    red: { bg: '#B71C1C', light: '#EF9A9A', name: 'Mordor' },
    yellow: { bg: '#F9A825', light: '#FFF59D', name: 'Harad & Rhûn' },
    green: { bg: '#2E7D32', light: '#A5D6A7', name: 'Reinos Elfos' },
    darkblue: { bg: '#1A237E', light: '#7986CB', name: 'Tierras Antiguas' },
    railroad: { bg: '#4E342E', light: '#8D6E63', name: 'Caminos' },
    utility: { bg: '#37474F', light: '#90A4AE', name: 'Artefactos' },
  },

  playerColors: ['#C0392B', '#2980B9', '#27AE60', '#F39C12', '#8E44AD', '#16A085'],

  tokens: [
    { id: 'ring', name: 'Anillo', icon: 'fa-ring' },
    { id: 'sword', name: 'Espada', icon: 'fa-khanda' },
    { id: 'shield', name: 'Escudo', icon: 'fa-shield-halved' },
    { id: 'horse', name: 'Caballo', icon: 'fa-horse' },
    { id: 'dragon', name: 'Dragón', icon: 'fa-dragon' },
    { id: 'wizard', name: 'Bastón', icon: 'fa-wand-magic-sparkles' },
    { id: 'crown', name: 'Corona', icon: 'fa-crown' },
    { id: 'leaf', name: 'Hoja', icon: 'fa-leaf' },
    { id: 'mountain', name: 'Montaña', icon: 'fa-mountain' },
    { id: 'eye', name: 'Ojo', icon: 'fa-eye' },
    { id: 'fire', name: 'Fuego', icon: 'fa-fire' },
    { id: 'skull', name: 'Calavera', icon: 'fa-skull' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta LA COMARCA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Las águilas te llevan al Camino del Norte. Si pasas por LA COMARCA, cobra $200.', action: 'move', target: 5 },
    { text: 'Las águilas te llevan al Camino del Sur. Si pasas por LA COMARCA, cobra $200.', action: 'move', target: 15 },
    { text: 'Las águilas te llevan al Camino del Este. Si pasas por LA COMARCA, cobra $200.', action: 'move', target: 25 },
    { text: 'Las águilas te llevan al Camino del Oeste. Si pasas por LA COMARCA, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza al artefacto más cercano. Si no está reclamado, puedes tomarlo.', action: 'nearest', type: 'utility' },
    { text: 'Avanza al camino más cercano. Si no está reclamado, puedes tomarlo.', action: 'nearest', type: 'railroad' },
    { text: 'El Banco de Rivendel te devuelve $50.', action: 'money', amount: 50 },
    { text: 'Ganas el favor del pueblo. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Carta de Gandalf: sal de las Mazmorras de Barad-dûr gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡A las Mazmorras de Barad-dûr! Capturado sin pasar por LA COMARCA.', action: 'gotojail' },
    { text: 'Trampa de orcos: retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Convocas al consejo de Elrond. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Reparaciones tras la batalla: $25 por aldea y $100 por castillo.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa por perturbar la paz: $15.', action: 'money', amount: -15 },
    { text: 'Montas a sombra veloz hasta el siguiente camino.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta LA COMARCA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Hallazgo en las minas de Moria. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Tributo de Gondor. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Festival en la Comarca. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Botín de un troll caído. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Seguro del Consejo Blanco. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Segundo premio en los Juegos del Norte. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Vendes reliquias élficas. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Honorarios de sanador. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Carta de Gandalf: sal de las Mazmorras de Barad-dûr gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Reparación de caminos: $40.', action: 'money', amount: -40 },
    { text: 'Peaje en puente de piedra: $15.', action: 'money', amount: -15 },
    { text: 'Heridas de batalla: paga $50.', action: 'money', amount: -50 },
    { text: 'Entrenamiento en Rivendel: $50.', action: 'money', amount: -50 },
    { text: 'Reconstrucción de reinos: $25 por aldea, $100 por castillo.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡A las Mazmorras de Barad-dûr! Capturado sin pasar por LA COMARCA.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Tierra Media',
    centerTitle: 'Tierra Media',
    centerTagline: 'Un Anillo para dominarlos a todos',
    welcomeLog: '¡La Comunidad se reúne! Que gane quien unifique la Tierra Media.',
    winMessage: 'Ha forjado un imperio digno de los Reyes de Gondor.',
    goName: 'LA COMARCA',
    jailName: 'Mazmorras de Barad-dûr',
    parkingName: 'Tierras Libres',
    chanceName: 'Destino',
    fortuneName: 'Saber',
    chanceDeckTitle: '⚔️ Carta del Destino',
    fortuneDeckTitle: '📜 Pergamino del Saber',
    railroadLabel: 'Camino Real',
    utilityLabel: 'Artefacto ancestral',
    jailFreeCard: 'carta de Gandalf',
    jailEmoji: '⛓️',
    parkingEmoji: '🏕️',
    buildings: {
      house: 'aldea',
      houses: 'aldeas',
      houseEmoji: '🛖',
      houseMarker: '▪',
      hotel: 'castillo',
      hotels: 'castillos',
      hotelEmoji: '🏰',
      rowLabel: 'Asentamientos',
      buildHouse: 'Aldea',
      buildHotel: 'Castillo',
      supplyHouses: 'Aldeas',
      supplyHotels: 'Castillos',
      noHousesLeft: 'No quedan aldeas en el banco.',
      noHotelsLeft: 'No quedan castillos en el banco.',
      sellBeforeMortgage: 'Vende aldeas y castillos antes de hipotecar.',
      sellFundsHint: 'Hipoteca reinos o vende aldeas/castillos en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>LA COMARCA</strong> y cobra $200',
      'Reclama reinos, cobra tributos y construye <strong>aldeas y castillos</strong>',
      'Completa regiones del mismo color para monopolio',
      '<strong>Negocia</strong> tierras, oro y cartas de Gandalf',
      'Si no compras, el reino se <strong>subasta</strong>',
      'Tributos y multas van a <strong>Tierras Libres</strong>',
      'Hipoteca fortalezas para obtener oro',
      'El último señor en pie gobierna la Tierra Media',
    ],
  },

  style: {
    fontFamily: "'Cinzel', 'Outfit', serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700;800&family=Outfit:wght@400;600;700&display=swap',
    bodyBg: `
      radial-gradient(circle at 18% 12%, rgba(180,83,9,0.18), transparent 30%),
      radial-gradient(circle at 82% 22%, rgba(30,64,175,0.14), transparent 32%),
      linear-gradient(135deg, #1a1208 0%, #1c1917 55%, #292524 100%)`,
    vars: {
      '--bg': '#1c1917',
      '--surface': '#292524',
      '--surface2': '#44403c',
      '--accent': '#d97706',
      '--accent2': '#b91c1c',
      '--text': '#fafaf9',
      '--text-muted': '#a8a29e',
      '--board-bg': '#3f3f46',
      '--board-border': '#27272a',
      '--board-center-bg': 'radial-gradient(ellipse at center, #57534e, #292524)',
      '--cell-bg': '#fef3c7',
      '--cell-text': '#292524',
    },
  },
};
