import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'KONOHA', desc: 'Cobra $200 al completar una vuelta' },
  { name: 'Ichiraku Ramen' },
  { name: 'Misión' },
  { name: 'Academia Ninja' },
  { name: 'Tributo del Hokage', desc: 'Paga $200' },
  { name: 'Ruta del Comercio' },
  { name: 'País de las Olas' },
  { name: 'Tesoro' },
  { name: 'Puente de Zabuza' },
  { name: 'Kirigakure' },
  { name: 'Prisión de Orochimaru', desc: 'Solo visita' },
  { name: 'Desierto de Suna' },
  { name: 'Chakra Natural' },
  { name: 'Sunagakure' },
  { name: 'Residencia del Kazekage' },
  { name: 'Ruta del Viento' },
  { name: 'Iwagakure' },
  { name: 'Misión' },
  { name: 'Cantera de Iwa' },
  { name: 'Valle del Fin' },
  { name: 'Zona de Descanso', desc: 'Descansa aquí' },
  { name: 'Kumogakure' },
  { name: 'Tesoro' },
  { name: 'Distrito Uchiha' },
  { name: 'Bosque Senju' },
  { name: 'Ruta del Rayo' },
  { name: 'Nube de Kumo' },
  { name: 'Niebla de Kiri' },
  { name: 'Laboratorio Orochimaru' },
  { name: 'Otogakure' },
  { name: '¡A la Prisión!', desc: 'Capturado sin pasar por KONOHA' },
  { name: 'Monte Myoboku' },
  { name: 'Bosque de la Muerte' },
  { name: 'Misión' },
  { name: 'Monte Hokage' },
  { name: 'Ruta del Fuego' },
  { name: 'Tesoro' },
  { name: 'Puerta de Konoha' },
  { name: 'Impuesto ANBU', desc: 'Paga $100' },
  { name: 'Torre del Hokage' },
];

export default {
  id: 'naruto',
  name: 'Naruto',
  icon: '🍥',
  tagline: 'Domina aldeas, misiones y el camino del ninja.',

  colors: {
    brown: { bg: '#92400E', light: '#FCD34D', name: 'Konoha Inicial' },
    lightblue: { bg: '#0369A1', light: '#7DD3FC', name: 'Misiones Clásicas' },
    pink: { bg: '#BE185D', light: '#F9A8D4', name: 'Aldea de la Arena' },
    orange: { bg: '#C2410C', light: '#FDBA74', name: 'Aldea de la Roca' },
    red: { bg: '#B91C1C', light: '#FCA5A5', name: 'Regiones del Trueno' },
    yellow: { bg: '#CA8A04', light: '#FDE047', name: 'Grandes Aldeas' },
    green: { bg: '#15803D', light: '#86EFAC', name: 'Clanes Legendarios' },
    darkblue: { bg: '#1E3A8A', light: '#93C5FD', name: 'Leyendas de Konoha' },
    railroad: { bg: '#7C2D12', light: '#FDBA74', name: 'Rutas Ninja' },
    utility: { bg: '#6D28D9', light: '#C4B5FD', name: 'Técnicas Especiales' },
  },

  playerColors: ['#F97316', '#3B82F6', '#EF4444', '#EAB308', '#8B5CF6', '#14B8A6'],

  tokens: [
    { id: 'kunai', name: 'Kunai', icon: 'fa-khanda' },
    { id: 'scroll', name: 'Pergamino', icon: 'fa-scroll' },
    { id: 'fire', name: 'Fuego', icon: 'fa-fire' },
    { id: 'leaf', name: 'Hoja', icon: 'fa-leaf' },
    { id: 'bolt', name: 'Rayo', icon: 'fa-bolt' },
    { id: 'wind', name: 'Viento', icon: 'fa-wind' },
    { id: 'eye', name: 'Sharingan', icon: 'fa-eye' },
    { id: 'frog', name: 'Sapo', icon: 'fa-frog' },
    { id: 'snake', name: 'Serpiente', icon: 'fa-staff-snake' },
    { id: 'star', name: 'Estrella', icon: 'fa-star' },
    { id: 'shield', name: 'Escudo', icon: 'fa-shield-halved' },
    { id: 'hand', name: 'Selos', icon: 'fa-hand-sparkles' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta KONOHA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Salto a Ruta del Comercio. Si pasas por KONOHA, cobra $200.', action: 'move', target: 5 },
    { text: 'Salto a Ruta del Viento. Si pasas por KONOHA, cobra $200.', action: 'move', target: 15 },
    { text: 'Salto a Ruta del Rayo. Si pasas por KONOHA, cobra $200.', action: 'move', target: 25 },
    { text: 'Salto a Ruta del Fuego. Si pasas por KONOHA, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza a la técnica especial más cercana. Si no está reclamada, puedes adquirirla.', action: 'nearest', type: 'utility' },
    { text: 'Avanza a la ruta ninja más cercana. Si no está reclamada, puedes adquirirla.', action: 'nearest', type: 'railroad' },
    { text: 'Recompensa de misión rank C: cobra $50.', action: 'money', amount: 50 },
    { text: 'Ganas el examen chunin. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Pergamino de escape: sal de la Prisión gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡A la Prisión! Capturado sin pasar por KONOHA.', action: 'gotojail' },
    { text: 'Genjutsu en el camino: retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Convocas una cumbre de Kage. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Reparación de infraestructura: $25 por puesto y $100 por fortaleza.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa del consejo ninja: paga $15.', action: 'money', amount: -15 },
    { text: 'Toma la siguiente ruta ninja disponible.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta KONOHA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Recompensa por renegado capturado. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Tesoro de la Aldea Oculta. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Festival del Fuego. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Misión bien pagada. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Patrocinio del daimyo. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Segundo premio en torneo. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Vendes pergaminos raros. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Entrenamiento con un sannin. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Pergamino de escape: sal de la Prisión gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Reparación del barrio ninja: $40.', action: 'money', amount: -40 },
    { text: 'Peaje en frontera: $15.', action: 'money', amount: -15 },
    { text: 'Hospital ninja: $50.', action: 'money', amount: -50 },
    { text: 'Material de entrenamiento: $50.', action: 'money', amount: -50 },
    { text: 'Mantenimiento en tus aldeas: $25 por puesto, $100 por fortaleza.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡A la Prisión! Capturado sin pasar por KONOHA.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Naruto',
    centerTitle: 'Naruto',
    centerTagline: 'El camino del ninja no termina',
    welcomeLog: '¡Bienvenidos al mundo shinobi! Que gane el mejor estratega.',
    winMessage: 'Ha conquistado el tablero como un verdadero Hokage.',
    goName: 'KONOHA',
    jailName: 'Prisión de Orochimaru',
    parkingName: 'Zona de Descanso',
    chanceName: 'Misión',
    fortuneName: 'Tesoro',
    chanceDeckTitle: '📜 Misión',
    fortuneDeckTitle: '💰 Tesoro',
    railroadLabel: 'Ruta ninja',
    utilityLabel: 'Técnica especial',
    jailFreeCard: 'pergamino de escape',
    jailEmoji: '⛓️',
    parkingEmoji: '🍥',
    buildings: {
      house: 'puesto',
      houses: 'puestos',
      houseEmoji: '⛺',
      houseMarker: '▪',
      hotel: 'fortaleza',
      hotels: 'fortalezas',
      hotelEmoji: '🏯',
      rowLabel: 'Infraestructura',
      buildHouse: 'Puesto',
      buildHotel: 'Fortaleza',
      supplyHouses: 'Puestos',
      supplyHotels: 'Fortalezas',
      noHousesLeft: 'No quedan puestos en el banco.',
      noHotelsLeft: 'No quedan fortalezas en el banco.',
      sellBeforeMortgage: 'Vende puestos y fortalezas antes de hipotecar.',
      sellFundsHint: 'Hipoteca aldeas o vende puestos/fortalezas en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>KONOHA</strong> y cobra $200',
      'Reclama aldeas, cobra peajes y construye <strong>puestos y fortalezas</strong>',
      'Completa regiones del mismo color para monopolio',
      '<strong>Negocia</strong> territorios, ryo y pergaminos con otros ninjas',
      'Si no compras, la aldea se <strong>subasta</strong>',
      'Multas y tributos van a la <strong>Zona de Descanso</strong>',
      'Hipoteca aldeas para obtener ryo',
      'El último ninja en pie se corona campeón',
    ],
  },

  style: {
    fontFamily: "'Outfit', system-ui, sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&display=swap',
    bodyBg: `
      radial-gradient(circle at 20% 12%, rgba(249,115,22,0.2), transparent 30%),
      radial-gradient(circle at 80% 18%, rgba(59,130,246,0.16), transparent 32%),
      linear-gradient(135deg, #1a1208 0%, #1c1917 55%, #292524 100%)`,
    vars: {
      '--bg': '#1c1917',
      '--surface': '#292524',
      '--surface2': '#44403c',
      '--accent': '#f97316',
      '--accent2': '#2563eb',
      '--text': '#fafaf9',
      '--text-muted': '#a8a29e',
      '--board-bg': '#9a3412',
      '--board-border': '#7c2d12',
      '--board-center-bg': 'radial-gradient(ellipse at center, #ea580c, #7c2d12)',
      '--cell-bg': '#fef3c7',
      '--cell-text': '#292524',
    },
  },
};
