import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'PRE-FIESTA', desc: 'Cobra $200 al dar otra vuelta' },
  { name: 'Shots Bar' },
  { name: 'Giro Loco' },
  { name: 'Cervecería' },
  { name: 'Multa: Llegaste tarde', desc: 'Paga $200' },
  { name: 'Uber de Vuelta' },
  { name: 'Barra de Gin' },
  { name: 'El Cumple' },
  { name: 'Barra de Ron' },
  { name: 'Mescal Corner' },
  { name: 'El Baño', desc: 'Solo visita' },
  { name: 'Pista de Baile' },
  { name: 'DJ Booth' },
  { name: 'Lounge VIP' },
  { name: 'Terraza Chill' },
  { name: 'Taxi Fiesta' },
  { name: 'Karaoke' },
  { name: 'Giro Loco' },
  { name: 'Sala de Juegos' },
  { name: 'Fotomatón' },
  { name: 'Sofá del Chill', desc: 'Descansa aquí' },
  { name: 'Discoteca' },
  { name: 'El Cumple' },
  { name: 'Barra Libre' },
  { name: 'Pista LED' },
  { name: 'Limusina' },
  { name: 'Rooftop' },
  { name: 'Pool Party' },
  { name: 'Barra de Champaña' },
  { name: 'After Party' },
  { name: '¡Te echaron!', desc: 'Directo sin pasar por PRE-FIESTA' },
  { name: 'Salón VIP Oro' },
  { name: 'Salón VIP Platino' },
  { name: 'Giro Loco' },
  { name: 'Mansión Fiesta' },
  { name: 'Servicio VIP' },
  { name: 'El Cumple' },
  { name: 'Penthouse' },
  { name: 'Propina del DJ', desc: 'Paga $100' },
  { name: 'Mega Club' },
];

export default {
  id: 'party',
  name: 'Fiesta Total',
  icon: '🎉',
  tagline: 'Barras, discos, VIP y la resaca del siglo.',

  colors: {
    brown: { bg: '#92400E', light: '#FBBF24', name: 'Shots & Cerveza' },
    lightblue: { bg: '#7C3AED', light: '#C4B5FD', name: 'Barras de Licor' },
    pink: { bg: '#DB2777', light: '#F9A8D4', name: 'Zonas Chill' },
    orange: { bg: '#EA580C', light: '#FDBA74', name: 'Entretenimiento' },
    red: { bg: '#DC2626', light: '#FCA5A5', name: 'Discotecas' },
    yellow: { bg: '#EAB308', light: '#FEF08A', name: 'After & Rooftop' },
    green: { bg: '#059669', light: '#6EE7B7', name: 'VIP Premium' },
    darkblue: { bg: '#4C1D95', light: '#A78BFA', name: 'Mega Clubs' },
    railroad: { bg: '#DB2777', light: '#F9A8D4', name: 'Transporte Fiesta' },
    utility: { bg: '#6366F1', light: '#A5B4FC', name: 'Servicios' },
  },

  playerColors: ['#EC4899', '#8B5CF6', '#F59E0B', '#10B981', '#EF4444', '#06B6D4'],

  tokens: [
    { id: 'champagne', name: 'Copa de champaña', icon: 'fa-champagne-glasses' },
    { id: 'beer', name: 'Cerveza', icon: 'fa-beer-mug-empty' },
    { id: 'cocktail', name: 'Cóctel', icon: 'fa-martini-glass-citrus' },
    { id: 'wine', name: 'Copa de vino', icon: 'fa-wine-glass' },
    { id: 'music', name: 'Nota musical', icon: 'fa-music' },
    { id: 'headphones', name: 'Auriculares DJ', icon: 'fa-headphones' },
    { id: 'mic', name: 'Micrófono', icon: 'fa-microphone-lines' },
    { id: 'dice', name: 'Dados', icon: 'fa-dice' },
    { id: 'star', name: 'Estrella VIP', icon: 'fa-star' },
    { id: 'fire', name: 'Fuego', icon: 'fa-fire-flame-curved' },
    { id: 'bolt', name: 'Rayo', icon: 'fa-bolt' },
    { id: 'cake', name: 'Tarta', icon: 'fa-cake-candles' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta PRE-FIESTA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Uber de Vuelta te lleva al inicio de la ronda. Si pasas por PRE-FIESTA, cobra $200.', action: 'move', target: 5 },
    { text: 'Taxi Fiesta te lleva a la zona central. Si pasas por PRE-FIESTA, cobra $200.', action: 'move', target: 15 },
    { text: 'Limusina VIP te lleva al sur. Si pasas por PRE-FIESTA, cobra $200.', action: 'move', target: 25 },
    { text: 'Servicio VIP te lleva al norte. Si pasas por PRE-FIESTA, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza a la barra más cercana. Si no está comprada, puedes adquirirla.', action: 'nearest', type: 'utility' },
    { text: 'Avanza al transporte de fiesta más cercano. Si no está comprado, puedes adquirirlo.', action: 'nearest', type: 'railroad' },
    { text: 'El cumpleañero te invita un trago: cobra $50.', action: 'money', amount: 50 },
    { text: 'Ganas el concurso de shots. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Pase VIP de amigo del DJ. Sal de El Baño gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡Te echaron de la fiesta! Directo a El Baño sin pasar por PRE-FIESTA.', action: 'gotojail' },
    { text: 'Te tropezaste bailando: retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Invitas ronda a todos. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Reparaciones tras la fiesta: $25 por mesa y $100 por salón VIP.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa por romper un vaso: paga $15.', action: 'money', amount: -15 },
    { text: 'Siguiente transporte de fiesta disponible.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta PRE-FIESTA. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Herencia de tu tío bartender. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Propinas de la noche. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Es tu cumpleaños (otra vez). Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Te devuelven la entrada del club. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Seguro anti-resaca premium. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Segundo premio en el concurso de baile. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Vendes tus pulseras VIP. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Honorarios de DJ invitado. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Pase VIP de amigo del DJ. Sal de El Baño gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Pagas los vasos rotos de anoche: $40.', action: 'money', amount: -40 },
    { text: 'Multa por hacer ruido en el after: $15.', action: 'money', amount: -15 },
    { text: 'Visita a la clínica de resaca: $50.', action: 'money', amount: -50 },
    { text: 'Curso intensivo de mixología: $50.', action: 'money', amount: -50 },
    { text: 'Limpieza de tu zona VIP: $25 por mesa, $100 por salón VIP.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡Te echaron de la fiesta! Directo a El Baño sin pasar por PRE-FIESTA.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Fiesta Total',
    centerTitle: 'Fiesta Total',
    centerTagline: 'La noche es larga y el tablero también',
    welcomeLog: '¡Que empiece la fiesta! Que gane quien sobreviva hasta el amanecer.',
    winMessage: 'Ha dominado la noche y se lleva la corona del rey de la fiesta.',
    goName: 'PRE-FIESTA',
    jailName: 'El Baño',
    parkingName: 'Sofá del Chill',
    chanceName: 'Giro Loco',
    fortuneName: 'El Cumple',
    chanceDeckTitle: '🎲 Giro Loco',
    fortuneDeckTitle: '🎂 El Cumple',
    railroadLabel: 'Transporte de fiesta',
    utilityLabel: 'Barra / Servicio',
    jailFreeCard: 'pase VIP del DJ',
    jailEmoji: '🚽',
    parkingEmoji: '🛋️',
    buildings: {
      house: 'mesa',
      houses: 'mesas',
      houseEmoji: '🍸',
      houseMarker: '▪',
      hotel: 'salón VIP',
      hotels: 'salones VIP',
      hotelEmoji: '🪩',
      rowLabel: 'Montaje',
      buildHouse: 'Mesa',
      buildHotel: 'Salón VIP',
      supplyHouses: 'Mesas',
      supplyHotels: 'Salones VIP',
      noHousesLeft: 'No quedan mesas en el banco.',
      noHotelsLeft: 'No quedan salones VIP en el banco.',
      sellBeforeMortgage: 'Retira mesas y salones antes de hipotecar.',
      sellFundsHint: 'Hipoteca locales o vende mesas/salones VIP en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>PRE-FIESTA</strong> y cobra $200',
      'Compra barras y discos, cobra entradas y monta <strong>mesas y salones VIP</strong>',
      'Completa zonas del mismo color para monopolio',
      '<strong>Negocia</strong> locales, dinero y pases VIP con otros jugadores',
      'Si no compras, el local se <strong>subasta</strong>',
      'Multas y propinas van al <strong>Sofá del Chill</strong>',
      'Hipoteca locales para conseguir cash para la ronda',
      'El último en pie se corona rey de la fiesta',
    ],
  },

  style: {
    fontFamily: "'Outfit', system-ui, sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&display=swap',
    bodyBg: `
      radial-gradient(circle at 12% 15%, rgba(236,72,153,0.28), transparent 30%),
      radial-gradient(circle at 88% 18%, rgba(139,92,246,0.25), transparent 32%),
      radial-gradient(circle at 50% 90%, rgba(234,179,8,0.15), transparent 35%),
      linear-gradient(135deg, #0f0518 0%, #1a0a2e 50%, #2e1065 100%)`,
    vars: {
      '--bg': '#0f0518',
      '--surface': '#1a0a2e',
      '--surface2': '#2e1065',
      '--accent': '#ec4899',
      '--accent2': '#a855f7',
      '--text': '#fdf4ff',
      '--text-muted': '#c4b5fd',
      '--board-bg': '#7c3aed',
      '--board-border': '#5b21b6',
      '--board-center-bg': 'radial-gradient(ellipse at center, #ec4899, #7c3aed)',
      '--cell-bg': '#fdf4ff',
      '--cell-text': '#2e1065',
    },
  },
};
