import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'THE GARAGE', desc: 'Cobra $200 al cerrar otra ronda de funding' },
  { name: 'Reddit' },
  { name: 'Pitch Deck' },
  { name: 'Pinterest' },
  { name: 'Regulación SEC', desc: 'Paga $200' },
  { name: 'Sand Hill Road' },
  { name: 'Airbnb' },
  { name: 'Term Sheet' },
  { name: 'Uber' },
  { name: 'DoorDash' },
  { name: 'Due Diligence', desc: 'Solo visita' },
  { name: 'Instagram' },
  { name: 'Cloud Compute' },
  { name: 'Snapchat' },
  { name: 'TikTok' },
  { name: 'Route 101' },
  { name: 'Netflix' },
  { name: 'Pitch Deck' },
  { name: 'Spotify' },
  { name: 'Discord' },
  { name: 'Free Snacks Lounge', desc: 'Descansa aquí' },
  { name: 'Tesla' },
  { name: 'Term Sheet' },
  { name: 'SpaceX' },
  { name: 'OpenAI' },
  { name: 'VC Express' },
  { name: 'Google' },
  { name: 'Meta' },
  { name: 'Generative AI' },
  { name: 'LinkedIn' },
  { name: '¡A Due Diligence!', desc: 'Auditoría sin pasar por THE GARAGE' },
  { name: 'Apple' },
  { name: 'Microsoft' },
  { name: 'Pitch Deck' },
  { name: 'Adobe' },
  { name: 'Bay Area Loop' },
  { name: 'Term Sheet' },
  { name: 'Amazon' },
  { name: 'Impuesto Unicornio', desc: 'Paga $100' },
  { name: 'NVIDIA' },
];

export default {
  id: 'siliconvalley',
  name: 'Silicon Valley',
  icon: '🚀',
  tagline: 'Levanta rondas, escala startups y domina el ecosistema tech.',

  colors: {
    brown: { bg: '#78350F', light: '#FBBF24', name: 'Early Stage' },
    lightblue: { bg: '#0284C7', light: '#7DD3FC', name: 'Marketplace' },
    pink: { bg: '#DB2777', light: '#F9A8D4', name: 'Social Apps' },
    orange: { bg: '#EA580C', light: '#FDBA74', name: 'Streaming & Comunidad' },
    red: { bg: '#DC2626', light: '#FCA5A5', name: 'Deep Tech' },
    yellow: { bg: '#CA8A04', light: '#FDE047', name: 'Big Tech' },
    green: { bg: '#059669', light: '#6EE7B7', name: 'Software Giants' },
    darkblue: { bg: '#1E3A8A', light: '#93C5FD', name: 'Unicornios' },
    railroad: { bg: '#475569', light: '#94A3B8', name: 'Rutas de Inversión' },
    utility: { bg: '#6366F1', light: '#A5B4FC', name: 'Infraestructura' },
  },

  playerColors: ['#EF4444', '#3B82F6', '#10B981', '#F59E0B', '#8B5CF6', '#06B6D4'],

  tokens: [
    { id: 'rocket', name: 'Cohete', icon: 'fa-rocket' },
    { id: 'laptop', name: 'Laptop', icon: 'fa-laptop-code' },
    { id: 'chip', name: 'Chip', icon: 'fa-microchip' },
    { id: 'chart', name: 'Growth', icon: 'fa-chart-line' },
    { id: 'lightbulb', name: 'Idea', icon: 'fa-lightbulb' },
    { id: 'code', name: 'Código', icon: 'fa-code' },
    { id: 'wifi', name: 'Conexión', icon: 'fa-wifi' },
    { id: 'cloud', name: 'Cloud', icon: 'fa-cloud' },
    { id: 'robot', name: 'Robot', icon: 'fa-robot' },
    { id: 'bolt', name: 'Disrupción', icon: 'fa-bolt' },
    { id: 'gem', name: 'Unicornio', icon: 'fa-gem' },
    { id: 'brain', name: 'IA', icon: 'fa-brain' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta THE GARAGE. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Salto a Sand Hill Road. Si pasas por THE GARAGE, cobra $200.', action: 'move', target: 5 },
    { text: 'Salto a Route 101. Si pasas por THE GARAGE, cobra $200.', action: 'move', target: 15 },
    { text: 'Salto a VC Express. Si pasas por THE GARAGE, cobra $200.', action: 'move', target: 25 },
    { text: 'Salto a Bay Area Loop. Si pasas por THE GARAGE, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza a la infraestructura más cercana. Si no está comprada, puedes adquirirla.', action: 'nearest', type: 'utility' },
    { text: 'Avanza a la ruta de inversión más cercana. Si no está comprada, puedes adquirirla.', action: 'nearest', type: 'railroad' },
    { text: 'Grant del acelerador Y Combinator: cobra $50.', action: 'money', amount: 50 },
    { text: 'Tu demo viral arrasa Product Hunt. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Safe note de respaldo: sal de Due Diligence gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡A Due Diligence! Auditoría sin pasar por THE GARAGE.', action: 'gotojail' },
    { text: 'Bug crítico en producción: retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Organizas un hackathon corporativo. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Mantenimiento de servidores: $25 por desk y $100 por HQ.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa por incumplir GDPR: paga $15.', action: 'money', amount: -15 },
    { text: 'Toma la siguiente ruta de inversión disponible.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta THE GARAGE. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Exit secundario inesperado. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Ronda Serie A cerrada. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Tu startup es portada de TechCrunch. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Devolución de créditos AWS. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Seguro de responsabilidad tech. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Segundo premio en demo day. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Vendes equity secundario. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Consultoría para Big Tech. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Safe note de respaldo: sal de Due Diligence gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Parche de seguridad urgente: $40.', action: 'money', amount: -40 },
    { text: 'Licencias SaaS vencidas: $15.', action: 'money', amount: -15 },
    { text: 'Abogados de propiedad intelectual: $50.', action: 'money', amount: -50 },
    { text: 'Bootcamp de liderazgo: $50.', action: 'money', amount: -50 },
    { text: 'Mantenimiento en tus startups: $25 por desk, $100 por HQ.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡A Due Diligence! Auditoría sin pasar por THE GARAGE.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Silicon Valley',
    centerTitle: 'Silicon Valley',
    centerTagline: 'Disrupt or be disrupted',
    welcomeLog: '¡Bienvenidos al valle! Que gane quien escale mejor.',
    winMessage: 'Ha construido el unicornio definitivo del tablero.',
    goName: 'THE GARAGE',
    jailName: 'Due Diligence',
    parkingName: 'Free Snacks Lounge',
    chanceName: 'Pitch Deck',
    fortuneName: 'Term Sheet',
    chanceDeckTitle: '📊 Pitch Deck',
    fortuneDeckTitle: '📝 Term Sheet',
    railroadLabel: 'Ruta de inversión',
    utilityLabel: 'Infraestructura',
    jailFreeCard: 'safe note de respaldo',
    jailEmoji: '🔍',
    parkingEmoji: '🍕',
    buildings: {
      house: 'desk',
      houses: 'desks',
      houseEmoji: '💻',
      houseMarker: '▪',
      hotel: 'HQ',
      hotels: 'HQs',
      hotelEmoji: '🏢',
      rowLabel: 'Equipos',
      buildHouse: 'Desk',
      buildHotel: 'HQ',
      supplyHouses: 'Desks',
      supplyHotels: 'HQs',
      noHousesLeft: 'No quedan desks en el banco.',
      noHotelsLeft: 'No quedan HQs en el banco.',
      sellBeforeMortgage: 'Vende desks y HQs antes de hipotecar.',
      sellFundsHint: 'Hipoteca startups o vende desks/HQs en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>THE GARAGE</strong> y cobra $200',
      'Compra startups, cobra royalties y construye <strong>desks y HQs</strong>',
      'Completa verticales del mismo color para monopolio',
      '<strong>Negocia</strong> equity, cash y safe notes con otros fundadores',
      'Si no compras, la startup se <strong>subasta</strong>',
      'Multas y fees van al <strong>Free Snacks Lounge</strong>',
      'Hipoteca startups para levantar liquidez',
      'El último unicornio en pie gana el valle',
    ],
  },

  style: {
    fontFamily: "'Outfit', system-ui, sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&display=swap',
    bodyBg: `
      radial-gradient(circle at 18% 14%, rgba(99,102,241,0.22), transparent 32%),
      radial-gradient(circle at 82% 20%, rgba(16,185,129,0.16), transparent 30%),
      linear-gradient(135deg, #0a0f1a 0%, #111827 55%, #1e293b 100%)`,
    vars: {
      '--bg': '#0f172a',
      '--surface': '#1e293b',
      '--surface2': '#334155',
      '--accent': '#22d3ee',
      '--accent2': '#a855f7',
      '--text': '#f8fafc',
      '--text-muted': '#94a3b8',
      '--board-bg': '#312e81',
      '--board-border': '#4338ca',
      '--board-center-bg': 'radial-gradient(ellipse at center, #4f46e5, #1e1b4b)',
      '--cell-bg': '#f8fafc',
      '--cell-text': '#0f172a',
    },
  },
};
