import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'TATOOINE', desc: 'Cobra $200 al completar el circuito' },
  { name: 'Mos Espa' },
  { name: 'La Fuerza' },
  { name: 'Anchorhead' },
  { name: 'Impuesto Imperial', desc: 'Paga $200' },
  { name: 'Hiperruta Corelliana' },
  { name: 'Naboo' },
  { name: 'El Consejo' },
  { name: 'Alderaan' },
  { name: 'Kamino' },
  { name: 'Celda Imperial', desc: 'Solo visita' },
  { name: 'Niveles Bajos' },
  { name: 'Reactor de Energía' },
  { name: 'Distrito del Senado' },
  { name: 'Torre del Jedi' },
  { name: 'Hiperruta del Borde' },
  { name: 'Mygeeto' },
  { name: 'La Fuerza' },
  { name: 'Felucia' },
  { name: 'Saleucami' },
  { name: 'Cantina Mos Eisley', desc: 'Descansa aquí' },
  { name: 'Mustafar' },
  { name: 'El Consejo' },
  { name: 'Geonosis' },
  { name: 'Utapau' },
  { name: 'Hiperruta del Rim' },
  { name: 'Bespin' },
  { name: 'Hoth' },
  { name: 'Escudo Deflector' },
  { name: 'Yavin 4' },
  { name: '¡A la Celda Imperial!', desc: 'Capturado por stormtroopers' },
  { name: 'D\'Qar' },
  { name: 'Ajan Kloss' },
  { name: 'La Fuerza' },
  { name: 'Ach-To' },
  { name: 'Hiperruta Desconocida' },
  { name: 'El Consejo' },
  { name: 'Estrella de la Muerte' },
  { name: 'Tributo Sith', desc: 'Paga $100' },
  { name: 'Starkiller Base' },
];

export default {
  id: 'starwars',
  name: 'Star Wars',
  icon: '⚔️',
  tagline: 'Conquista la galaxia, domina rutas hiperespaciales y forja tu imperio.',

  colors: {
    brown: { bg: '#8B6914', light: '#D4A84B', name: 'Mundos del Desierto' },
    lightblue: { bg: '#1565C0', light: '#90CAF9', name: 'Mundos del Núcleo' },
    pink: { bg: '#AD1457', light: '#F48FB1', name: 'Coruscant' },
    orange: { bg: '#E65100', light: '#FFCC80', name: 'Frentes Clon' },
    red: { bg: '#B71C1C', light: '#EF5350', name: 'Mundos Separatistas' },
    yellow: { bg: '#F9A825', light: '#FFF59D', name: 'Bases Rebeldes' },
    green: { bg: '#2E7D32', light: '#81C784', name: 'Resistencia' },
    darkblue: { bg: '#0D1B2A', light: '#415A77', name: 'Superarmas' },
    railroad: { bg: '#37474F', light: '#78909C', name: 'Hiperrutas' },
    utility: { bg: '#455A64', light: '#B0BEC5', name: 'Tecnología' },
  },

  playerColors: ['#E74C3C', '#3498DB', '#2ECC71', '#F1C40F', '#9B59B6', '#1ABC9C'],

  tokens: [
    { id: 'xwing', name: 'Caza estelar', icon: 'fa-jet-fighter' },
    { id: 'falcon', name: 'Halconero', icon: 'fa-shuttle-space' },
    { id: 'saber', name: 'Sable láser', icon: 'fa-wand-sparkles' },
    { id: 'trooper', name: 'Stormtrooper', icon: 'fa-helmet-safety' },
    { id: 'droid', name: 'Droide', icon: 'fa-robot' },
    { id: 'rebel', name: 'Rebelde', icon: 'fa-user-astronaut' },
    { id: 'star', name: 'Estrella', icon: 'fa-star' },
    { id: 'moon', name: 'Luna', icon: 'fa-moon' },
    { id: 'rocket', name: 'Cohete', icon: 'fa-rocket' },
    { id: 'satellite', name: 'Satélite', icon: 'fa-satellite-dish' },
    { id: 'explosion', name: 'Explosión', icon: 'fa-explosion' },
    { id: 'mask', name: 'Máscara', icon: 'fa-mask' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta TATOOINE. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Salto hiperespacial a Hiperruta Corelliana. Si pasas por TATOOINE, cobra $200.', action: 'move', target: 5 },
    { text: 'Salto hiperespacial a Hiperruta del Borde. Si pasas por TATOOINE, cobra $200.', action: 'move', target: 15 },
    { text: 'Salto hiperespacial a Hiperruta del Rim. Si pasas por TATOOINE, cobra $200.', action: 'move', target: 25 },
    { text: 'Salto hiperespacial a Hiperruta Desconocida. Si pasas por TATOOINE, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza a la tecnología más cercana. Si no está reclamada, puedes adquirirla.', action: 'nearest', type: 'utility' },
    { text: 'Avanza a la hiperruta más cercana. Si no está reclamada, puedes adquirirla.', action: 'nearest', type: 'railroad' },
    { text: 'El Banco de la República te devuelve $50.', action: 'money', amount: 50 },
    { text: 'Ganas el favor de un consejo de clan. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Credencial de contrabandista: sal de la Celda Imperial gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡A la Celda Imperial! Capturado sin pasar por TATOOINE.', action: 'gotojail' },
    { text: 'Emboscada de cazas TIE: retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Convocas una cumbre del Alto Mando. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Reparaciones tras el asalto: $25 por puesto y $100 por base estelar.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa por contrabando: paga $15.', action: 'money', amount: -15 },
    { text: 'Salto a la siguiente hiperruta disponible.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta TATOOINE. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Botín de un convoy imperial caído. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Tributo de un sistema aliado. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Día de la Victoria en Endor. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Recompensa de la Alianza Rebelde. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Seguro del Consejo Rebelde. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Segundo premio en carreras de Pod. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Vendes piezas de droide en el mercado negro. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Honorarios de piloto de élite. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Credencial de contrabandista: sal de la Celda Imperial gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Reparación de hangar: $40.', action: 'money', amount: -40 },
    { text: 'Peaje en puerto espacial: $15.', action: 'money', amount: -15 },
    { text: 'Gastos médicos en bacta: $50.', action: 'money', amount: -50 },
    { text: 'Entrenamiento en la Academia: $50.', action: 'money', amount: -50 },
    { text: 'Reconstrucción de instalaciones: $25 por puesto, $100 por base estelar.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡A la Celda Imperial! Capturado sin pasar por TATOOINE.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Star Wars',
    centerTitle: 'Star Wars',
    centerTagline: 'Que la Fuerza te acompañe en el tablero',
    welcomeLog: '¡Que comience la conquista galáctica! Que gane quien domine la galaxia.',
    winMessage: 'Ha forjado un imperio digno de un Lord Sith… o un maestro Jedi.',
    goName: 'TATOOINE',
    jailName: 'Celda Imperial',
    parkingName: 'Cantina Mos Eisley',
    chanceName: 'La Fuerza',
    fortuneName: 'El Consejo',
    chanceDeckTitle: '✨ La Fuerza',
    fortuneDeckTitle: '📡 El Consejo',
    railroadLabel: 'Hiperruta',
    utilityLabel: 'Tecnología estratégica',
    jailFreeCard: 'credencial de contrabandista',
    jailEmoji: '🔒',
    parkingEmoji: '🍺',
    buildings: {
      house: 'puesto avanzado',
      houses: 'puestos avanzados',
      houseEmoji: '🏗️',
      houseMarker: '▪',
      hotel: 'base estelar',
      hotels: 'bases estelares',
      hotelEmoji: '🛸',
      rowLabel: 'Instalaciones',
      buildHouse: 'Puesto',
      buildHotel: 'Base estelar',
      supplyHouses: 'Puestos',
      supplyHotels: 'Bases estelares',
      noHousesLeft: 'No quedan puestos avanzados en el banco.',
      noHotelsLeft: 'No quedan bases estelares en el banco.',
      sellBeforeMortgage: 'Vende puestos y bases antes de hipotecar.',
      sellFundsHint: 'Hipoteca planetas o vende puestos/bases en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>TATOOINE</strong> y cobra $200',
      'Reclama planetas, cobra peajes y construye <strong>puestos y bases estelares</strong>',
      'Completa sectores del mismo color para monopolio',
      '<strong>Negocia</strong> mundos, créditos y credenciales con otros jugadores',
      'Si no compras, el planeta se <strong>subasta</strong>',
      'Multas y tributos van a la <strong>Cantina Mos Eisley</strong>',
      'Hipoteca sistemas para obtener créditos',
      'El último señor de la galaxia en pie gana',
    ],
  },

  style: {
    fontFamily: "'Orbitron', 'Outfit', sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Orbitron:wght@400;600;700;800&family=Outfit:wght@400;600;700&display=swap',
    bodyBg: `
      radial-gradient(circle at 15% 12%, rgba(255,232,31,0.12), transparent 28%),
      radial-gradient(circle at 85% 18%, rgba(59,130,246,0.18), transparent 32%),
      radial-gradient(ellipse at 50% 100%, rgba(139,92,246,0.08), transparent 40%),
      linear-gradient(135deg, #020408 0%, #0a0f1a 50%, #111827 100%)`,
    vars: {
      '--bg': '#050a12',
      '--surface': '#0f172a',
      '--surface2': '#1e293b',
      '--accent': '#ffe81f',
      '--accent2': '#ef4444',
      '--text': '#f1f5f9',
      '--text-muted': '#94a3b8',
      '--board-bg': '#1e3a5f',
      '--board-border': '#0f2744',
      '--board-center-bg': 'radial-gradient(ellipse at center, #1e40af, #0f172a)',
      '--cell-bg': '#e2e8f0',
      '--cell-text': '#0f172a',
    },
  },
};
