import { buildBoard } from './shared.js';

const cellMeta = [
  { name: 'INICIO', desc: 'Cobra $200 al dar la vuelta al mundo' },
  { name: 'Vaticano' },
  { name: 'Destino' },
  { name: 'Mónaco' },
  { name: 'Aranceles', desc: 'Paga $200' },
  { name: 'Ruta Polar' },
  { name: 'Maldivas' },
  { name: 'Tesoro' },
  { name: 'Fiyi' },
  { name: 'Hawái' },
  { name: 'Aduana', desc: 'Solo tránsito' },
  { name: 'Grecia' },
  { name: 'Petróleo Global' },
  { name: 'Italia' },
  { name: 'España' },
  { name: 'Ruta Atlántica' },
  { name: 'Uruguay' },
  { name: 'Destino' },
  { name: 'Chile' },
  { name: 'Argentina' },
  { name: 'Zona Neutral', desc: 'Descansa aquí' },
  { name: 'Egipto' },
  { name: 'Tesoro' },
  { name: 'Sudáfrica' },
  { name: 'Kenia' },
  { name: 'Ruta del Pacífico' },
  { name: 'India' },
  { name: 'China' },
  { name: 'Energía Solar' },
  { name: 'Japón' },
  { name: '¡A la Aduana!', desc: 'Control fronterizo directo' },
  { name: 'Alemania' },
  { name: 'Francia' },
  { name: 'Destino' },
  { name: 'Reino Unido' },
  { name: 'Ruta Transcontinental' },
  { name: 'Tesoro' },
  { name: 'Estados Unidos' },
  { name: 'Impuesto de Lujo', desc: 'Paga $100' },
  { name: 'Canadá' },
];

export default {
  id: 'world',
  name: 'Países del Mundo',
  icon: '🌍',
  tagline: 'Conquista naciones, rutas globales y recursos del planeta.',

  colors: {
    brown: { bg: '#6B4226', light: '#A67B5B', name: 'Microestados' },
    lightblue: { bg: '#1E90FF', light: '#87CEFA', name: 'Islas del Pacífico' },
    pink: { bg: '#E07A5F', light: '#F2CC8F', name: 'Mediterráneo' },
    orange: { bg: '#D97706', light: '#FBBF24', name: 'Cono Sur' },
    red: { bg: '#B91C1C', light: '#FCA5A5', name: 'África' },
    yellow: { bg: '#CA8A04', light: '#FDE047', name: 'Asia' },
    green: { bg: '#15803D', light: '#86EFAC', name: 'Europa' },
    darkblue: { bg: '#1E3A8A', light: '#60A5FA', name: 'Potencias Mundiales' },
    railroad: { bg: '#0F766E', light: '#5EEAD4', name: 'Rutas Globales' },
    utility: { bg: '#475569', light: '#94A3B8', name: 'Recursos' },
  },

  playerColors: ['#DC2626', '#2563EB', '#16A34A', '#EAB308', '#9333EA', '#0891B2'],

  tokens: [
    { id: 'globe', name: 'Globo terráqueo', icon: 'fa-earth-americas' },
    { id: 'passport', name: 'Pasaporte', icon: 'fa-passport' },
    { id: 'plane', name: 'Avión', icon: 'fa-plane' },
    { id: 'ship', name: 'Crucero', icon: 'fa-ship' },
    { id: 'flag', name: 'Bandera', icon: 'fa-flag' },
    { id: 'compass', name: 'Brújula', icon: 'fa-compass' },
    { id: 'mountain', name: 'Montaña', icon: 'fa-mountain' },
    { id: 'camera', name: 'Cámara', icon: 'fa-camera' },
    { id: 'suitcase', name: 'Maleta', icon: 'fa-suitcase' },
    { id: 'map', name: 'Mapa', icon: 'fa-map' },
    { id: 'anchor', name: 'Ancla', icon: 'fa-anchor' },
    { id: 'binoculars', name: 'Binoculares', icon: 'fa-binoculars' },
  ],

  board: buildBoard(cellMeta),

  cityCards: [
    { text: 'Avanza hasta INICIO. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Vuelo charter a Ruta Polar. Si pasas por INICIO, cobra $200.', action: 'move', target: 5 },
    { text: 'Vuelo charter a Ruta Atlántica. Si pasas por INICIO, cobra $200.', action: 'move', target: 15 },
    { text: 'Vuelo charter a Ruta del Pacífico. Si pasas por INICIO, cobra $200.', action: 'move', target: 25 },
    { text: 'Vuelo charter a Ruta Transcontinental. Si pasas por INICIO, cobra $200.', action: 'move', target: 35 },
    { text: 'Avanza al recurso más cercano. Si no está comprado, puedes adquirirlo.', action: 'nearest', type: 'utility' },
    { text: 'Avanza a la ruta global más cercana. Si no está comprada, puedes adquirirla.', action: 'nearest', type: 'railroad' },
    { text: 'Subvención de la ONU: cobra $50.', action: 'money', amount: 50 },
    { text: 'Ganas el premio Nobel de la Paz. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Visado diplomático. Sal de la Aduana gratis. Guarda esta carta.', action: 'jailFree' },
    { text: '¡A la Aduana! Control fronterizo sin pasar por INICIO.', action: 'gotojail' },
    { text: 'Retraso en conexión: retrocede 3 casillas.', action: 'back', steps: 3 },
    { text: 'Organizas una cumbre mundial. Paga $50 a cada jugador.', action: 'payEach', amount: 50 },
    { text: 'Mantenimiento de infraestructura: $25 por puesto y $100 por embajada.', action: 'repairs', house: 25, hotel: 100 },
    { text: 'Multa aduanera: paga $15.', action: 'money', amount: -15 },
    { text: 'Toma la siguiente ruta global disponible.', action: 'nearest', type: 'railroad' },
  ],

  fortuneCards: [
    { text: 'Avanza hasta INICIO. Cobra $200.', action: 'move', target: 0, collectGo: true },
    { text: 'Herencia de un tío viajero. Cobra $200.', action: 'money', amount: 200 },
    { text: 'Dividendos de inversión internacional. Cobra $50.', action: 'money', amount: 50 },
    { text: 'Día nacional de tu país. Cobra $10 de cada jugador.', action: 'collectEach', amount: 10 },
    { text: 'Devolución de impuestos de importación. Cobra $20.', action: 'money', amount: 20 },
    { text: 'Seguro de viaje premium. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Segundo premio en la Expo Mundial. Cobra $25.', action: 'money', amount: 25 },
    { text: 'Vendes sellos raros. Cobra $45.', action: 'money', amount: 45 },
    { text: 'Consultoría para la ONU. Cobra $100.', action: 'money', amount: 100 },
    { text: 'Visado diplomático. Sal de la Aduana gratis. Guarda esta carta.', action: 'jailFree' },
    { text: 'Reparación de carreteras nacionales: $40.', action: 'money', amount: -40 },
    { text: 'Estacionamiento en aeropuerto: $15.', action: 'money', amount: -15 },
    { text: 'Visita médica en el extranjero: $50.', action: 'money', amount: -50 },
    { text: 'Matrícula en universidad internacional: $50.', action: 'money', amount: -50 },
    { text: 'Mantenimiento en tus territorios: $25 por puesto, $100 por embajada.', action: 'repairs', house: 25, hotel: 100 },
    { text: '¡A la Aduana! Control fronterizo sin pasar por INICIO.', action: 'gotojail' },
  ],

  strings: {
    gameName: 'Países del Mundo',
    centerTitle: 'Países del Mundo',
    centerTagline: 'Domina el planeta',
    welcomeLog: '¡Bienvenidos al tablero mundial! Que gane el mejor estratega.',
    winMessage: 'Ha conquistado el mundo con diplomacia y fortuna.',
    goName: 'INICIO',
    jailName: 'Aduana',
    parkingName: 'Zona Neutral',
    chanceName: 'Destino',
    fortuneName: 'Tesoro',
    chanceDeckTitle: '🌍 Carta Destino',
    fortuneDeckTitle: '💎 Tesoro Mundial',
    railroadLabel: 'Ruta Global',
    utilityLabel: 'Recurso estratégico',
    jailFreeCard: 'visado diplomático',
    jailEmoji: '🛃',
    parkingEmoji: '🌐',
    buildings: {
      house: 'puesto',
      houses: 'puestos',
      houseEmoji: '🏕️',
      houseMarker: '▪',
      hotel: 'embajada',
      hotels: 'embajadas',
      hotelEmoji: '🏛️',
      rowLabel: 'Infraestructura',
      buildHouse: 'Puesto',
      buildHotel: 'Embajada',
      supplyHouses: 'Puestos',
      supplyHotels: 'Embajadas',
      noHousesLeft: 'No quedan puestos en el banco.',
      noHotelsLeft: 'No quedan embajadas en el banco.',
      sellBeforeMortgage: 'Vende la infraestructura antes de hipotecar.',
      sellFundsHint: 'Hipoteca territorios o vende puestos/embajadas en el panel de acciones, luego pulsa',
    },
    rules: [
      'Pasa por <strong>INICIO</strong> y cobra $200',
      'Compra países, cobra peajes y construye <strong>puestos y embajadas</strong>',
      'Completa regiones del mismo color para monopolio',
      '<strong>Negocia</strong> territorios, dinero y visados con otros jugadores',
      'Si no compras, el territorio se <strong>subasta</strong>',
      'Impuestos y multas van a la <strong>Zona Neutral</strong>',
      'Hipoteca territorios para obtener liquidez',
      'El último jugador en pie domina el mundo',
    ],
  },

  style: {
    fontFamily: "'Outfit', system-ui, sans-serif",
    fontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&display=swap',
    bodyBg: `
      radial-gradient(circle at 20% 15%, rgba(37,99,235,0.2), transparent 32%),
      radial-gradient(circle at 80% 25%, rgba(22,163,74,0.15), transparent 30%),
      linear-gradient(135deg, #0c1929 0%, #0f172a 55%, #1e293b 100%)`,
    vars: {
      '--bg': '#0f172a',
      '--surface': '#1e293b',
      '--surface2': '#334155',
      '--accent': '#38bdf8',
      '--accent2': '#f59e0b',
      '--text': '#f1f5f9',
      '--text-muted': '#94a3b8',
      '--board-bg': '#1d4ed8',
      '--board-border': '#1e40af',
      '--board-center-bg': 'radial-gradient(ellipse at center, #2563eb, #1e3a8a)',
      '--cell-bg': '#f8fafc',
      '--cell-text': '#1e293b',
    },
  },
};
